### PR TITLE
Fixed Vte versions problem

### PR DESCRIPTION
**Pull request by 163gal**
* Forcing Pippy to use Vte 2.90 avoid problems with computers with newer Vte libraries

### CODE REVIEW

**Comment by quozl** [comment]
This breaks activity start on Ubuntu 15.10 which has Vte 2.91 and not Vte 2.90.

```
ValueError: Namespace Vte not available for version 2.90
```

#163gal, what problems made you change this?

**Comment by 163gal** [comment]
I changed it because on some computers sugar-build do not have Vte 2.91, and most computers with Vte 2.91 still have Vte 2.90. Maybe it can be replaced with an if and hasattr?

**Comment by quozl** [comment]
Okay, thanks.  We don't use sugar-build for end users, so what sugar-build has doesn't matter.  If that's the only problem, then does it work without this patch?  Then whatever version is available is used.

**Comment by 163gal** [comment]
I don't know what Vte version does Sugar for end-users have. If it has Vte 2.90, it would work without this patch, if it has Vte 2.90 and 2.91 too, but if it has only Vte 2.91 (Which is unlikely) it won't.

**Comment by quozl** [comment]
I've removed the patch, tested again on Ubuntu 15.10 which has only Vte 2.91 and not Vte 2.90, and it works fine.  I don't see why it is unlikely.  Have I missed something?

**Comment by 163gal** [comment]
Oops, my mistake. It will start Pippy, it won't start a script exported from Pippy as a bundle.

**Comment by quozl** [comment]
How can I test that?  It says "Please select an activity icon".

**Comment by 163gal** [comment]
Export as a bundle and then try to start the newly created activity.

**Comment by quozl** [comment]
When I type a test program:

```
print "hello world"
```

and change the activity name to "hello", and press "export as a bundle", the error is "Please select an activity icon".

**Comment by 163gal** [comment]
That's not an error, it should pop a window with some options to choose.

**Comment by quozl** [comment]
It does not pop a window.  Activity log shows:

```
Traceback (most recent call last):
  File "/home/olpc/Activities/Pippy.activity/pippy_app.py", line 754, in _dialog
    dialog = IconDialog()
  File "/home/olpc/Activities/Pippy.activity/icondialog.py", line 98, in __init__
    self.icons = self.build_scroll()
  File "/home/olpc/Activities/Pippy.activity/icondialog.py", line 143, in build_scroll
    icons = self.build_icons()
  File "/home/olpc/Activities/Pippy.activity/icondialog.py", line 158, in build_icons
    for icon in get_user_icons():
  File "/home/olpc/Activities/Pippy.activity/icondialog.py", line 68, in get_user_icons
    home = get_usericons_icons()
  File "/home/olpc/Activities/Pippy.activity/icondialog.py", line 57, in get_usericons_icons
    path = get_user_path()
  File "/home/olpc/Activities/Pippy.activity/icondialog.py", line 52, in get_user_path
    shutil.copy(DEFAULT_ICON, os.path.join(path, DEFAULT_NAME))
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 20] Not a directory: '/home/olpc/.icons/default-pippy.svg'
```

**Comment by 163gal** [comment]
Well, that's another error I didn't know...

**Comment by walterbender** [comment]
I have not seen that error (I get the pop up window). This is on Ubuntu?

On Sun, Dec 20, 2015 at 6:38 PM, Ezequiel Pereira <notifications@github.com>
wrote:

> Well, that's another error I didn't know...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterbender/Pippy/pull/25#issuecomment-166165273>.
>



-- 
Walter Bender
Sugar Labs
http://www.sugarlabs.org

**Comment by quozl** [comment]
Yes, on Ubuntu.

**Pull request merged**
