### PR TITLE
Fixed the problem of naming of tabs while adding new tabs

### PR DESCRIPTION
**Pull request by rohitsakala**
Suppose there are n tabs opened and if anyone closes a tab(not the last one) and again add a new tab then the name of the tab will be coinciding with the other tab name.

### CODE REVIEW

**Comment by walterbender** [comment]
could you explain how your patch fixes the problem?

**Comment by rohitsakala** [comment]
self.get_n_pages returns us the no of tabs currently present. So, I think we should not use get_n_pages() function for naming.

I created a self.tabdex instead of tabdex and incrementing it everytime a new tab is opened. By this, whenever a new tab is addedd it will always have an incremented value.

**Comment by rohitsakala** [comment]
self.get_n_pages returns us the no of tabs currently present. So, I think we should not use get_n_pages() function for naming.

I created a self.tabdex instead of tabdex and incrementing it everytime a new tab is opened. By this, whenever a new tab is added it will always have an incremented value rather than previous values.

**Comment by walterbender** [comment]
So you are sying that get_n_pages doesn't tell you about the new tab being opened?

**Comment by rohitsakala** [comment]
No..It just returns the no of tabs opened at that moment and we are calculating the name of it by that  function. So, by this the above said bug occurs.

**Pull request merged**
